---
destination : _site
lsi         : false
highlighter : pygments
permalink   : pretty
markdown    : kramdown
include     : [".htaccess"]
exclude	    : ["rsync-site.sh", ".git", ".gitignore", "Gemfile", "Gemfile.lock", "script", "vendor", "tmp"]
url         : "http://kyleniemeyer.com"

author:
    name : Kyle Niemeyer
    email : kyle.niemeyer@gmail.com
    github : kyleniemeyer
    twitter : kyleniemeyer

kramdown:
    parse_block_html: true

gems:
  - jekyll-seo-tag
